name: Build and publish the master ckan-solr image
on:
  schedule:
    - cron: '15 5 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build ckan-solr master
        uses: docker/build-push-action@v3
        with:
          context: solr-8
          file: solr-8/Dockerfile
          build-args: |
            CKAN_BRANCH=master
          push: true
          tags: |
            ckan/ckan-solr:master

